import React from 'react'

const BoundingBox = (props) => {
    const getOnlyLetters = (input) => {
        const lettersArray = input.replace(/[^a-zA-Z]/g, ' ').split(' ');
        const formattedText = lettersArray
            .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
            .join(' ');
        return formattedText.trim();
    };
    //#region Rendering the detections generated by AI models
    const drawDetections = (detections) => {
        if (!detections || Object.keys(detections).length === 0) {
            return null;
        }
        return Object.entries(detections).map(([defectName, defectPoints], idx) => {
            const [x1, y1, x2, y2] = defectPoints;

            return (
                <g key={`${defectName}-${idx}`}>
                    <rect
                        x={x1}
                        y={y1}
                        width={x2 - x1}
                        height={y2 - y1}
                        stroke='yellow'
                        strokeWidth="1"
                        fill="none"
                    />
                    <text x={x1} y={y1 - 3} fill="yellow" fontSize="10" fontWeight='400'>{getOnlyLetters(defectName)}</text>
                </g>
            );
        });
    };
    //#endregion
    return (
        <svg width="100" height="100" className='absolute top-0 left-0 w-full h-full'>
            {drawDetections(props.detections)}
        </svg>
    )
}

export default BoundingBox
